[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

lib_deps =
    h2zero/NimBLE-Arduino @ ^2.5.1
    bblanchon/ArduinoJson @ ^7.4.3
    alvarowolfx/ESP32QRCodeReader @^1.1.0
    knolleary/PubSubClient @ ^2.8

board_build.partitions = huge_app.csv
build_flags = -DBOARD_HAS_PSRAM

upload_speed = 921600
monitor_speed = 115200
