upstream ntfy_mgr_api {
    # Should point to the same port as the ntfy-mgr-server upstream in ntfy-mgr.nginx
    server 127.0.0.1:$UPSTREAM_PORT;
}

server {
    listen $NTFY_MGR_WEB_PORT;

    root /opt/ntfy-mgr/ntfy-mgr-web/dist;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript;

    location /api/ {
        proxy_pass http://ntfy_mgr_api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
