<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>svn.viewer.loader</RootNamespace>
    <NoWarn>$(NoWarn);IDE0063;IDE0290</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\SVNLogo.ico" />
    <Resource Include="assets\SVNLogo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3344-prerelease" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
  </ItemGroup>

  <PropertyGroup Condition="'$(BuildingInsideVisualStudio)'=='true'">
    <DefineConstants>$(DefineConstants);BUILT_INSIDE_VS</DefineConstants>
  </PropertyGroup>

</Project>