#!/usr/bin/env python3
"""Generate platform-specific file type constants from shared/file-types.json."""

import json
import os
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED_FILE = REPO_ROOT / "shared" / "file-types.json"

BACKEND_OUTPUT = REPO_ROOT / "remote-cp-backend" / "app" / "generated_file_types.py"
WEB_OUTPUT = REPO_ROOT / "remote-cp-web" / "src" / "generated" / "fileTypes.ts"
ANDROID_OUTPUT = (
    REPO_ROOT
    / "remote-cp-android"
    / "app"
    / "src"
    / "main"
    / "java"
    / "com"
    / "runerback"
    / "remotecp"
    / "data"
    / "FileTypes.kt"
)


def load_shared() -> dict:
    with SHARED_FILE.open("r", encoding="utf-8") as f:
        return json.load(f)


def generate_backend(data: dict) -> str:
    image_exts = ", ".join(repr(ext) for ext in data["imageExtensions"])
    video_exts = ", ".join(repr(ext) for ext in data["videoExtensions"])
    file_exts = ", ".join(repr(ext) for ext in data["fileExtensions"])
    file_input_accept = ", ".join(sorted(data["fileExtensions"]))

    return f'''\
# Generated by scripts/generate_file_types.py. Do not edit manually.

ALLOWED_IMAGE_EXTENSIONS = {{{image_exts}}}
ALLOWED_VIDEO_EXTENSIONS = {{{video_exts}}}
ALLOWED_FILE_EXTENSIONS = {{{file_exts}}}
FILE_INPUT_ACCEPT = ",".join(sorted(ALLOWED_FILE_EXTENSIONS))
'''


def generate_web(data: dict) -> str:
    image_exts = ", ".join(repr(ext) for ext in data["imageExtensions"])
    video_exts = ", ".join(repr(ext) for ext in data["videoExtensions"])
    file_exts = ", ".join(repr(ext) for ext in data["fileExtensions"])
    mime_entries = ",\n".join(
        f'  {repr(mime)}: {repr(ext)}' for mime, ext in data["imageMimeMap"].items()
    )
    default_ext = repr(data["defaultImageExtension"])

    return f'''\
// Generated by scripts/generate_file_types.py. Do not edit manually.

export const IMAGE_EXTENSIONS = [{image_exts}];
export const VIDEO_EXTENSIONS = [{video_exts}];
export const FILE_EXTENSIONS = [{file_exts}];

export const IMAGE_ACCEPT = "image/*";
export const VIDEO_ACCEPT = "video/mp4,.mp4";
export const FILE_ACCEPT = FILE_EXTENSIONS.join(",");

export const IMAGE_MIME_MAP: Record<string, string> = {{
{mime_entries},
}};

export const DEFAULT_IMAGE_EXTENSION = {default_ext};
'''


def generate_android(data: dict) -> str:
    return '''\
package com.runerback.remotecp.data

// Generated by scripts/generate_file_types.py. Do not edit manually.

object FileTypes {
    const val IMAGE_MIME = "image/*"
    const val VIDEO_MIME = "video/*"
    val FILE_MIME_ARRAY = arrayOf("*/*")
}
'''


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    data = load_shared()

    write_file(BACKEND_OUTPUT, generate_backend(data))
    write_file(WEB_OUTPUT, generate_web(data))
    write_file(ANDROID_OUTPUT, generate_android(data))

    print(f"Generated: {BACKEND_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"Generated: {WEB_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"Generated: {ANDROID_OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
